# Inspired from Iceberg theme.
[colors.primary]
background = '0x161821'
foreground = '0xc6c8d1'

[colors.cursor]
text = '0x161821'
cursor = '0xd2d4de'

# Normal colors
[colors.normal]
black = '0x161821'
red = '0xe27878'
green = '0xb4be82'
yellow = '0xe2a478'
blue = '0x84a0c6'
magenta = '0xa093c7'
cyan = '0x89b8c2'
white = '0xc6c8d1'

# Bright colors
[colors.bright]
black = '0x676767'
red = '0xFF6D67'
green = '0x5FF967'
yellow = '0xFEFB67'
blue = '0x6871FF'
magenta = '0xFF76FF'
cyan = '0x5FFDFF'
white = '0xFEFFFF'

